name: WF local
on: [push, workflow_dispatch]
jobs:
    buildJob:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Build en cours"
    testJob:
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "Test en cours"